name: PHP Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: PHP Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd):/app composer:2 install

      - name: Generate the key
        run: docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd):/app -w /app php:8.2 /app/bin/console lexik:jwt:generate-keypair

      - name: Test
        run: docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $(pwd):/app -w /app php:8.2 /app/vendor/bin/phpunit
